/*
 * This source file was generated by the Gradle 'init' task
 */
package sequencer.project;

import sequencer.project.audio.musicroom;
import sequencer.project.model.instrument;
import sequencer.project.model.note;
import sequencer.project.model.sequence;
import sequencer.project.model.track;

public class App {
    public static void main(String[] args) {
        System.out.println("running...");
        musicroom musicRoom = new musicroom();
        sequence mySequence = new sequence(musicRoom);
        mySequence.addTrack("Teenage Drums");
        track myTrack = mySequence.getTrack(0);
        myTrack.addNote(0, 60, 1, 127);
        myTrack.addNote(1, 64, 1, 127);
        myTrack.addNote(2, 62, 1, 127);
        myTrack.addNote(3, 64, 1, 127);
        myTrack.addNote(4, 60, 1, 127);
        myTrack.addNote(5, 64, 1, 127);
        myTrack.addNote(6, 62, 1, 127);
        myTrack.addNote(7, 64, 1, 127);
        mySequence.play();
        System.out.println("done");
    }
}
